apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  gateways:
    ingress:
      enabled: true
      service:
        type: LoadBalancer
    additionalIngress:
      httpbin-ingress:
        enabled: true
        namespace: httpbin
  tracing:
    type: None
  policy:
    type: Istiod
  proxy:
    accessLogging:
      file:
        name: /dev/stdout
  addons:
    grafana:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
  telemetry:
    type: Istiod
  version: v2.5